# Generated by Django 5.2.6 on 2026-01-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='core.organization'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='agent_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.agentconfig'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='agent_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agentdefinition'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='core.scenario'),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='core.organization'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='llm_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.llmprovider'),
        ),
    ]
