# Generated by Django 5.2.6 on 2026-01-26 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUtility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('utility_type', models.CharField(choices=[('forecasting', 'Forecasting'), ('optimization', 'Optimization'), ('transformation', 'Transformation'), ('custom', 'Custom')], max_length=50)),
                ('required_inputs', models.JSONField(default=dict, help_text='e.g. columns, types')),
                ('outputs', models.JSONField(default=dict)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_utilities', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='utilities',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.agentutility'),
        ),
    ]
