# Generated by Django 5.2.6 on 2026-02-09 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentutility_agentdefinition_utilities'),
        ('core', '0003_costaccounting'),
        ('workflows', '0002_compiledworkflow_workflowrun_nodeexecution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='api_key_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encryptedsecret'),
        ),
        migrations.CreateModel(
            name='AgentCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('cost_input', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_output', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('latency_ms', models.IntegerField()),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tools_used', models.JSONField(default=list)),
                ('temperature', models.FloatField()),
                ('max_tokens', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='agents.agentdefinition')),
                ('node_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_calls', to='workflows.nodeexecution')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_calls', to='workflows.workflowrun')),
            ],
            options={
                'indexes': [models.Index(fields=['agent_definition', 'timestamp'], name='agents_agen_agent_d_ac5e27_idx'), models.Index(fields=['workflow_run', 'timestamp'], name='agents_agen_workflo_0a53f4_idx')],
            },
        ),
    ]
