# Generated by Django 5.2.6 on 2026-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_llmprovider_api_key_secret_agentcalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='is_summarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='original_memory_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='size_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='ttl_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
