# Generated by Django 5.2.6 on 2026-02-09 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentmemory_access_count_agentmemory_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinitionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('llm_provider_snapshot', models.JSONField(default=dict)),
                ('agent_config_snapshot', models.JSONField(default=dict)),
                ('utilities_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True)),
                ('agent_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agents.agentdefinition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('agent_definition', 'version_number')},
            },
        ),
    ]
