# Generated by Django 5.2.6 on 2026-02-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentdefinitionversion'),
        ('core', '0003_costaccounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='agentutility',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_utilities', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='core.organization'),
        ),
    ]
