# Generated by Django 5.2.6 on 2026-02-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agentconfig_organization_and_more'),
        ('core', '0003_costaccounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization'),
        ),
    ]
