# Generated by Django 5.2.6 on 2026-02-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_agentdefinition_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentutility',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='agentdefinition',
            name='utilities',
        ),
        migrations.RenameField(
            model_name='agentdefinitionversion',
            old_name='utilities_snapshot',
            new_name='tools_snapshot',
        ),
    ]
