# Generated by Django 5.2.6 on 2026-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_remove_agentutility_organization_and_more'),
        ('tools', '0004_remove_toolschema_allowed_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='agents', to='tools.tool'),
        ),
        migrations.DeleteModel(
            name='AgentUtility',
        ),
    ]
