# Generated by Django 5.2.6 on 2026-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentdefinition_tools_delete_agentutility'),
        ('tools', '0010_alter_tool_python_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='agent_configs', to='tools.tool'),
        ),
    ]
