# Generated by Django 5.2.6 on 2026-01-25 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('database', 'Database'), ('csv', 'CSV'), ('api', 'API')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fetch_mode', models.CharField(choices=[('live', 'Live'), ('batch', 'Batch')], max_length=20)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario_overrides', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schema_definition', models.JSONField(default=dict, help_text='JSON schema definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tables', to='core.organization')),
            ],
        ),
    ]
