# Generated by Django 5.2.6 on 2026-01-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictable',
            name='physical_table_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
