# Generated by Django 5.2.6 on 2026-01-26 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_dynamictable_physical_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_snapshot', models.JSONField(default=dict)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='datasources.dynamictable')),
            ],
        ),
    ]
