# Generated by Django 5.2.6 on 2026-02-10 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_dynamictablehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='last_fetched_at',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='table_name',
        ),
        migrations.CreateModel(
            name='SourceTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schema_definition', models.JSONField(blank=True, default=dict)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='datasources.datasource')),
            ],
            options={
                'unique_together': {('data_source', 'name')},
            },
        ),
    ]
