# Generated by Django 5.2.6 on 2026-02-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_remove_datasource_last_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictable',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='datasources.datasource'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SourceTable',
        ),
    ]
