# Generated by Django 5.2.6 on 2026-02-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costaccounting'),
        ('datasources', '0005_dynamictable_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='dynamictable',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tables', to='core.organization'),
        ),
    ]
