# Generated by Django 5.2.6 on 2026-01-26 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_dynamictablehistory'),
        ('transforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformdefinition',
            name='input_tables',
            field=models.ManyToManyField(blank=True, related_name='input_to_transforms', to='datasources.dynamictable'),
        ),
        migrations.CreateModel(
            name='TransformRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_table', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_by_run', to='datasources.dynamictable')),
                ('transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='transforms.transformdefinition')),
            ],
        ),
    ]
