# Generated by Django 5.2.6 on 2026-02-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transforms', '0002_transformdefinition_input_tables_transformrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformdefinition',
            name='auto_discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transformdefinition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transformdefinition',
            name='input_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transformdefinition',
            name='key',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transformdefinition',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transformdefinition',
            name='python_path',
            field=models.CharField(blank=True, help_text='Python path to the Transform Class', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transformdefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
