# Generated by Django 5.2.6 on 2026-02-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costaccounting'),
        ('transforms', '0003_transformdefinition_auto_discovered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transforms', to='core.organization'),
        ),
    ]
