# Generated by Django 5.2.6 on 2026-02-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costaccounting'),
        ('workflows', '0002_compiledworkflow_workflowrun_nodeexecution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.organization'),
        ),
    ]
