# Generated by Django 5.2.6 on 2026-02-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
