# Generated by Django 5.2.6 on 2026-02-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_delete_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='is_exposed_to_apps',
            field=models.BooleanField(default=True, help_text='Whether this node can be used as a widget source in applications'),
        ),
    ]
