# Generated by Django 5.2.6 on 2026-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflownode_is_exposed_to_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this workflow is published and available as a component for Apps'),
        ),
    ]
