# Generated by Django 5.2.6 on 2026-02-09 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_costaccounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('workflow_duration', 'Workflow Duration'), ('node_duration', 'Node Duration'), ('agent_latency', 'Agent Latency'), ('transform_duration', 'Transform Duration'), ('api_response_time', 'API Response Time')], max_length=50)),
                ('resource_id', models.UUIDField()),
                ('resource_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='ms', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='analytics_p_metric__cd80ae_idx'), models.Index(fields=['organization', 'timestamp'], name='analytics_p_organiz_367704_idx')],
            },
        ),
    ]
