# Generated by Django 5.2.6 on 2026-02-09 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentmemory_access_count_agentmemory_expires_at_and_more'),
        ('core', '0003_costaccounting'),
        ('tools', '0001_initial'),
        ('workflows', '0002_compiledworkflow_workflowrun_nodeexecution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolschema',
            name='allowed_organizations',
            field=models.ManyToManyField(blank=True, related_name='allowed_tools', to='core.organization'),
        ),
        migrations.AddField(
            model_name='toolschema',
            name='execution_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='toolschema',
            name='execution_type',
            field=models.CharField(choices=[('python_function', 'Python Function'), ('http_api', 'HTTP API'), ('database_query', 'Database Query'), ('shell_command', 'Shell Command')], default='http_api', max_length=50),
        ),
        migrations.AddField(
            model_name='toolschema',
            name='max_execution_time_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='toolschema',
            name='rate_limit_per_hour',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='toolschema',
            name='rate_limit_per_minute',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='toolschema',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agentdefinition')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_approvals', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tools.toolschema')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowrun')),
            ],
        ),
    ]
