# Generated by Django 5.2.6 on 2026-02-09 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolschema_allowed_organizations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSchemaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('execution_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tools.toolschema')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('tool_schema', 'version_number')},
            },
        ),
    ]
