# Generated by Django 5.2.6 on 2026-02-11 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costaccounting'),
        ('tools', '0003_toolschemaversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolschema',
            name='allowed_organizations',
        ),
        migrations.RemoveField(
            model_name='toolschema',
            name='organization',
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('key', models.SlugField(help_text='Unique key for tool identification (e.g. google_search)', unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('execution_mode', models.CharField(choices=[('synchronous', 'Synchronous (API/Function)'), ('asynchronous', 'Asynchronous (Background Job)')], default='synchronous', max_length=20)),
                ('api_config', models.JSONField(blank=True, default=dict)),
                ('python_path', models.CharField(blank=True, help_text='Dot path to python function', max_length=500)),
                ('worker_task', models.CharField(blank=True, help_text='Dot path to Django-Q task', max_length=500)),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('requires_approval', models.BooleanField(default=False)),
                ('max_execution_time_seconds', models.IntegerField(default=30)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_hour', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_organizations', models.ManyToManyField(blank=True, related_name='allowed_tools', to='core.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='toolexecution',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tools.tool'),
        ),
        migrations.CreateModel(
            name='ToolVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('execution_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tools.tool')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tool', 'version_number')},
            },
        ),
        migrations.DeleteModel(
            name='ToolSchemaVersion',
        ),
        migrations.DeleteModel(
            name='ToolSchema',
        ),
    ]
