# Generated by Django 5.2.6 on 2026-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_toolschema_allowed_organizations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='version',
        ),
        migrations.AlterField(
            model_name='tool',
            name='execution_mode',
            field=models.CharField(choices=[('synchronous', 'Synchronous (Blocking)'), ('asynchronous', 'Asynchronous (Background)')], default='synchronous', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='key',
            field=models.SlugField(help_text="Unique identifier (e.g. 'finance.npv')", unique=True),
        ),
    ]
