# Generated by Django 5.2.6 on 2026-02-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costaccounting'),
        ('tools', '0006_remove_tool_api_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.organization'),
        ),
    ]
