# Generated by Django 5.2.6 on 2026-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_tool_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='algo_parameters',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tool',
            name='api_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tool',
            name='max_execution_time_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tool',
            name='rate_limit_per_hour',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tool',
            name='rate_limit_per_minute',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='tool',
            name='worker_task',
            field=models.CharField(blank=True, help_text='Dot path to Django-Q task', max_length=500),
        ),
        migrations.AlterField(
            model_name='tool',
            name='execution_mode',
            field=models.CharField(choices=[('synchronous', 'Synchronous (API/Function)'), ('asynchronous', 'Asynchronous (Background Job)')], default='synchronous', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='input_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tool',
            name='python_path',
            field=models.CharField(blank=True, help_text='Dot path to python function', max_length=500),
        ),
    ]
