# Generated by Django 5.2.6 on 2026-02-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_remove_tool_algo_parameters_remove_tool_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='api_config',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='max_execution_time_seconds',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='rate_limit_per_hour',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='rate_limit_per_minute',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='worker_task',
        ),
        migrations.AddField(
            model_name='tool',
            name='algo_parameters',
            field=models.JSONField(default=dict, help_text='Algorithm Config (e.g. Sensitivity, Model Name)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='execution_mode',
            field=models.CharField(choices=[('synchronous', 'Synchronous (Blocking)'), ('asynchronous', 'Asynchronous (Background)')], default='synchronous', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='input_schema',
            field=models.JSONField(default=dict, help_text='Runtime Inputs (e.g. Table ID, Column)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='python_path',
            field=models.CharField(help_text="Python path to the Tool Class (e.g. 'tools.library.finance.NetPresentValue')", max_length=500, unique=True),
        ),
    ]
