# Generated by Django 5.2.6 on 2026-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_remove_tool_api_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='python_path',
            field=models.CharField(help_text="Python path to the Tool Class (e.g. 'tools.library.finance.NetPresentValue')", max_length=500),
        ),
    ]
