# Generated by Django 5.2.6 on 2026-01-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_runtime', '0001_initial'),
        ('core', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdefinition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_apps', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='apprun',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='apps_runtime.appdefinition'),
        ),
        migrations.AddField(
            model_name='apprun',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_runs', to='core.scenario'),
        ),
    ]
