# Generated by Django 5.2.6 on 2026-02-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_runtime', '0002_initial'),
        ('core', '0003_costaccounting'),
        ('workflows', '0005_delete_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appdefinition',
            old_name='is_public',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='entry_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_entries', to='workflows.workflownode'),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='icon',
            field=models.CharField(default='layout', max_length=50),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='core.organization'),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='primary_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_agents', to='workflows.workflownode'),
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
