# Generated by Django 5.2.6 on 2026-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_runtime', '0003_rename_is_public_appdefinition_is_published_and_more'),
        ('workflows', '0005_delete_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdefinition',
            name='entry_node',
        ),
        migrations.RemoveField(
            model_name='appdefinition',
            name='primary_agent',
        ),
        migrations.RemoveField(
            model_name='appdefinition',
            name='workflow',
        ),
        migrations.AddField(
            model_name='appdefinition',
            name='workflows',
            field=models.ManyToManyField(blank=True, related_name='apps', to='workflows.workflow'),
        ),
    ]
