# Generated by Django 5.2.6 on 2026-02-09 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_encryptedsecret_ipallowlist_ratelimitrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAccounting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_workflow_runs', models.IntegerField(default=0)),
                ('total_agent_calls', models.IntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('llm_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compute_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('storage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.organization')),
            ],
        ),
    ]
